language: java
jdk:
  - openjdk8
sudo: false
cache:
  directories:
    - $HOME/.m2
install: skip
script:
  - mvn install spring-boot:repackage
after_success:
  - bash <(curl -s https://codecov.io/bash)

