version: '3'

services:
  app:
    image: maven:3.6.3-jdk-11-openj9
    ports:
      - "8080:8080"
    restart: on-failure
    expose:
      - "8080"
    depends_on:
      - "database"
    links:
      - "database"
    volumes:
      - ./:/app
    working_dir: /app
    command: mvn install spring-boot:run
    environment:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
  database:
    image: mysql
    restart: always
    container_name: database-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=gear
    volumes:
      - db-data:/var/lib/mysql

    ports:
      - 6033:3306

volumes:
  db-data: